export const STARTSHIP_GET_ALL_START = 'STARTSHIP/GET_ALL/START';
export const STARTSHIP_GET_ALL_SUCCESS = 'STARTSHIP/GET_ALL/SUCCESS';
export const STARTSHIP_GET_ALL_ERROR = 'STARTSHIP/GET_ALL/ERROR';

export const STARTSHIP_SELECTED_START = 'STARTSHIP/SELECTED/START';
export const STARTSHIP_SELECTED_SUCCESS = 'STARTSHIP/SELECTED/SUCCESS';
export const STARTSHIP_SELECTED_ERROR = 'STARTSHIP/SELECTED/ERROR';